### ISSUE TITLE
UIラフ作成

### ISSUE THREAD

**Issue by zomatype** [0time-engineer/front-end#6]
## ✨ 概要

- Figmaにて、UIのラフを作成する

## 🔥 ゴール

- 機能やデザインの調整など

## 📄 参考資料

- https://www.figma.com/file/CdllXnuh67jzM37bok4TE8/%E7%84%A1%E9%A1%8C?type=design&node-id=0-1&t=yLlJe4YfPePq1wHP-0

## ✅ タスク

- [ ] xxx

**Comment by KRei0** [comment]
ver1.0完成とする
